name: deploy

on:
  workflow_call:
    inputs:
      release_version:
        type: string
        required: true
      environment:
        type: string
        required: true
      next_environment:
        type: string
        required: false
      deployment_statuses:
        type: string
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    secrets: inherit
    uses: oleksandrkudin/poc-ndp-workflows/.github/workflows/null_deploy.yaml@main
    with:
      unit: "poc-ndp-app1"
      release_version: ${{ inputs.release_version }}
      environment: ${{ inputs.environment }}
      next_environment: ${{ inputs.next_environment }}
      deployment_statuses: ${{ inputs.deployment_statuses }}
