name: deploy

on:
  workflow_call:
    inputs:
      release_version:
        type: string
        required: true
      environment:
        type: string
        required: true
      next_environment:
        type: string
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    if: ${{ inputs.next_environment != '' }}
    secrets: inherit
    uses: oleksandrkudin/poc-ndp-workflows/.github/workflows/update_environment.yaml@main
    with:
      unit: "poc-ndp-app1"
      release_version: ${{ inputs.release_version }}
      environment: ${{ inputs.environment }}
